# The name of the world where the gates are located
world: "world"

# Gates configuration
gates:
  # Example gate configuration
  # gate_name:
  #   location: !!org.bukkit.Location
  #     ==: org.bukkit.Location
  #     world: world
  #     x: 100.0
  #     y: 64.0
  #     z: 100.0
  #     pitch: 0.0
  #     yaw: 0.0
  #   mode: "random" # or "single"
  #   destinations:
  #     1: !!org.bukkit.Location
  #       ==: org.bukkit.Location
  #       world: world
  #       x: 200.0
  #       y: 70.0
  #       z: 200.0
  #       pitch: 0.0
  #       yaw: 0.0
  #     2: !!org.bukkit.Location
  #       ==: org.bukkit.Location
  #       world: world
  #       x: 300.0
  #       y: 70.0
  #       z: 300.0
  #       pitch: 0.0
  #       yaw: 0.0
  #   chances:
  #     1: 50
  #     2: 50
  #   disabled: false
